### ISSUE TITLE
师兄师姐你们好，想了解一下circAtlas的问题。

### ISSUE THREAD

**Issue by ChristopherLeeZG** [bioinfo-biols/CIRI-full#2]
您好，看到这几天circAtlas在数据更新，想请教您数据库中 full length 和  mature length的情况。

我发现有接近1/3的circRNA都存在【human_bed_v2.0.txt】提供的全长坐标，和【human_sequence_v2.0.txt】 文件中circRNA 两端的序列对不上，如下图所示。
![image](https://user-images.githubusercontent.com/40749917/225547743-ed3db2e5-a512-4461-b078-e945ff453761.png)

我看了CIRI-as和CIRI-full的算法，还有其他4个circRNA的鉴定软件，都有基于1-3形成BSJ位点来鉴定。那为什么mature length 的BSJ位点又变成了 1-2（这种情况在很多4个软件同时鉴定到的circRNA中也有）

祝好！

**Comment by Kevinzjy** [comment]
你好，这个可能是CIRI-full输出的序列是为全长序列。一般bed文件里BSJ位点是准确的，sequence文件中CIRI-full重构的序列可能BSJ附近的exon没有FSJ read支持，所以输出的序列会是partial reconstructed，可以以bed文件为准。

**Comment by ChristopherLeeZG** [comment]
您好，已经收到您的信件。我会及时阅读并回复。谢谢。                                                                       Lee.ZG

**Comment by ChristopherLeeZG** [comment]
好的。感谢您。也就是说，circRNA真实成环的情况下。首尾连接点，其实是bed文件的两端序列（exon1和exon3，BSJ），我这样理解对吗。
![image](https://user-images.githubusercontent.com/40749917/225568417-daf72f86-ea28-44ba-a864-a5c306f4787a.png)

非常感谢！

**Comment by Kevinzjy** [comment]
是的。对于没有包括BSJ位置的第二个 mature sequence，有可能是蓝色到绿色的exon junction 没有 FSJ read 支持，可以根据你们的分析和实验需求来选择是否保留这种序列。

<img width="514" alt="image" src="https://user-images.githubusercontent.com/10627200/225569200-f2d3b990-0e8c-4779-ba8a-82eadd12f9da.png">

**Comment by ChristopherLeeZG** [comment]
好的。非常感谢！
