### ISSUE TITLE
请问java -jar CIRI_full.jar RO2 -l的参数怎么设置?

### ISSUE THREAD

**Issue by junjunlab** [bioinfo-biols/CIRI-full#3]
老师,您好,感谢您们开发了这个很棒的工具, 请问 CIRI_full.jar RO2 的 -l 参数怎么设置呢?假如我是双端测序150bp,我是应该设置150还是300呢?感谢!

**Comment by Kevinzjy** [comment]
pe150的话设置 `-l 150` 就可以

**Comment by junjunlab** [comment]
好的,感谢解答!
